package com.github.danrog303.shelfspace.data.shelf;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.validator.constraints.Length;
import com.github.danrog303.shelfspace.data.profile.UserProfile;

import javax.validation.constraints.NotNull;
import java.util.List;

/**
 * Shelf created by the particular user. Shelf can be used to store {@link ShelfItem}s.
 */
@DynamoDBTable(tableName="shelf-space-shelves")
@Data @NoArgsConstructor @AllArgsConstructor
public class Shelf {
    /**
     * Unique identifier of the shelf.
     */
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String shelfId;

    /**
     * Name of the shelf. For example "Games" or "Sci-fi movies".
     */
    @DynamoDBAttribute
    @NotNull @Length(min=3, max=64)
    private String shelfName;

    /**
     * Unique identifier of the {@link UserProfile} which owns this shelf.
     */
    @DynamoDBAttribute
    private String ownerId;

    /**
     * Type of the shelf.
     */
    @DynamoDBAttribute
    @DynamoDBTypeConvertedEnum
    @NotNull
    private ShelfType shelfType;

    /**
     * List of items that are placed on this shelf
     */
    @DynamoDBAttribute
    private List<ShelfItem> items;
}
