package com.github.danrog303.shelfspace.data.shelf;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.fasterxml.jackson.annotation.JsonInclude;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.Range;

import javax.validation.constraints.NotNull;
import java.util.Date;

/**
 * A single item that was created on one of the user's shelves.
 * @see ShelfItemIntegrityValidator
 */
@DynamoDBDocument
@Data @NoArgsConstructor @AllArgsConstructor @EqualsAndHashCode
public class ShelfItem {
    /**
     * Unique identifier of the item.
     */
    @DynamoDBAttribute
    @DynamoDBAutoGeneratedKey
    private String itemId;

    /**
     * Title of the item - for example name of the book or the movie.
     */
    @DynamoDBAttribute
    @NotNull @Length(min=3, max=128)
    private String title;

    /**
     * Date of item creation. This field is generated automatically on item's creation and user
     * should not be able to overwrite it.
     */
    @DynamoDBAttribute
    @DynamoDBTypeConvertedTimestamp
    private Date creationDate;

    /**
     * Status of the item.
     */
    @DynamoDBAttribute
    @DynamoDBTypeConvertedEnum
    @NotNull
    private ShelfItemStatus status;

    /**
     * User's rate of this item - from 1 to 10 (can also be null, if user did not specify his rating).
     * If {@link ShelfItem#getStatus()} is equal to {@link ShelfItemStatus#PLANNED}, this
     * field should be equal to null and ignored.
     */
    @DynamoDBAttribute
    @Range(min=1, max=10)
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private Integer rating;

    /**
     * How many times user did finish this item?
     * If {@link ShelfItem#getStatus()} is not equal to {@link ShelfItemStatus#FINISHED}, this
     * field should be equal to null and ignored.
     * If {@link ShelfItem#getStatus()} is equal to {@link ShelfItemStatus#FINISHED}, this field cannot be null.
     */
    @DynamoDBAttribute
    @Range(min=1, max=2000)
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private Integer finishedCount;

}
